### ISSUE TITLE
No emails are being sent by the form

### ISSUE THREAD

**Issue by fnadde42** [splitbrain/dokuwiki-plugin-bureaucracy#119]
I copied the default form from the documentation and modified it to match my needs but when I try to send the form, no email is being sent by the server. I have double checked my emailadress in the form and checked my spam/trash in my email but I can't find it anywhere. I have recieved emails before from my dokuwiki installation so I know it can send emails.

Is there anything wrong with my form, cause I can't see it.

I'd be happy to supply anyone with more information to solve this weird problem.

My dokuwiki version: `Release 2014-09-29b "Hrun"`
I just downloaded the bureaucracy plugin: `Last updated on 2014-12-12`

```
<form>
Action mail me@email.se
Thanks "Valberedningen kommer att kontakta dig inom kort"

Fieldset "Kontakt"
Textbox  "Förnamn"
Textbox  "Efternamn"
number "Telefon"
email "Epost"

Fieldset "Kandidatur"
static "Vilken post kandiderar du till?"
yesno "Ordförande"
yesno "Vice Ordförande"
yesno "Kassör"
yesno "Sekreterare"
yesno "Ledamot"
yesno "Suppleant"
yesno "Revisor"
yesno "Valberedning"

Fieldset ""
submit "Skicka in kandidatur"
</form>
```

PS. I was just thinking; perhaps it's one of the other plugins interfering with bureaucracy? Does that happen?

**Comment by guntherito** [comment]
Hi,

I experience the same problems with the following setup:  

My Dokuwiki version: Release 2015-08-10a "Detritus"
Bureaucracy Plugin: 2016-07-06

The Thanks page appears and no errors are reported. However, no e-mails are sent. I tried several different addresses and domains.

Looking forward to any suggestions. Thanks!

**Comment by nickgreen43** [comment]
Hi,

Was this issue ever resolved? I am experiencing the same thing with my form not sending an email.

**Comment by Klap-in** [comment]
These sounds as quite general descriptions of the situation, and therefore it is difficult to react with specific advises.
Are the default functions of dokuwiki which use email working? 

Did you test the recommended plugin for if email is not working? Please see https://www.dokuwiki.org/plugin:bureaucracy

**Comment by nickgreen43** [comment]
Thank you sir! This helped. I got the SMTP plugin and it sent successfully.
Now to figure out why the yesno checkboxes aren't included in the email.

Best,

**Comment by Klap-in** [comment]
(Off-topic reaction: did you set default values? Please see plugin wiki page for how and for some examples to try)
