### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki-plugin-bureaucracy#126]
@Klap-in I think one of the recent PR merges broke a test. Not sure which one. Can you check?

**Comment by Klap-in** [comment]
Seems one test that fails, with an error that looks as a strange symptom. 
https://travis-ci.org/splitbrain/dokuwiki-plugin-bureaucracy/jobs/43374977

I think that I will see if it is reproducible.

**Comment by Klap-in** [comment]
The PR https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/pull/128 did build fine. So I think it was just an incident.

**Comment by splitbrain** [comment]
I let that test rerun and it did complete successfully. So yeah, seems to be a travis hickup.
