### ISSUE TITLE
No way to add but hide data?

### ISSUE THREAD

**Issue by webhamster** [splitbrain/dokuwiki-plugin-bureaucracy#127]
Hi!

As far as I see there is no way to have a public form, add the form data to a table, but hide this table from the user, right? This would be useful for, e.g., registration forms with more or less personal data.

I think, a reasonable addition to the pagemod plugin would therefore be a config option that activates the following policy: If the user has *no* write access to the form's page, and has no read access to the result page, and this config option is activated, then the pagemod action is accepted. 

If you like, I could provide a patch for this.

**Comment by soakindulge** [comment]
Yeah, it's a pity that Bureaucracy's Runas Option is not supported in Pagemod action. But It seems like a problem with pagemod plugin... Not sure if it's the right place to raise this issue.

Anyway, it's wonderful you could fix this problem lol

**Comment by Klap-in** [comment]
The Pagemod plugin has already a certain support for runas, at least it is part of the access check in the code..
Please check the documentation at https://www.dokuwiki.org/plugin:pagemod for its features. If you cannot reproduce this decribed behaviour, then I ask you to share simple examples that let me reproduce this misbehaviour.

The pagemod plugin is suitable for extending a table, please have a look at the examples.

**Comment by splitbrain** [comment]
no additional feedback provided
