### ISSUE TITLE
Pagemod plugin causes "No action defined - where should the data be sent to?"

### ISSUE THREAD

**Issue by jimmy-van** [splitbrain/dokuwiki-plugin-bureaucracy#131]
Similar issue to [issue #103](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/issues/103), noting this issue is reported in March 2015, after the November 2014 update.

A bureaucracy form is defined with:
> `<form>`
> action pagemod clininterventions:pilotresults add_intervention

The target page exists.
When attempting to submit the form with all the required fields complete, upon clicking submit, a:
> No action defined - where should the data be sent to?

message is returned, along with:

> ERROR: called action %s did not implement a run() function

_Other details_
If I attempt to access "info" for pagemod via the plugin manager, then
> The page cannot be displayed because an internal server error has occurred.

is displayed, so I probably haven't installed the pagemod plugin correctly.

This wiki is on an intranet with no internet access. All plugins are manually installed, so haven't been able to update post installation as [issue #103](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/issues/103) or the [pagemod documentation](https://www.dokuwiki.org/plugin:pagemod) suggests.
Files can be manually copied over if that is what the fix requires.

Any thoughts?

Thanks,
Jimmy

**Comment by splitbrain** [comment]
First of all this should be reported in the pagemod bugtracker. Also did you do what #103 suggests and copied the mentioned file to the bureaucracy plugin dir?

**Comment by Klap-in** [comment]
Manually copying files isn't required anymore. Use therefore the latest version of bureaucracy and pagemod.

**Comment by jimmy-van** [comment]
I am using both the latest versions of both plugins, downloaded and installed manually on February 20, 2015.
I have not manually copied/moved any files.

If it matters, I installed bureaucracy first, then pagemod.

**Comment by Klap-in** [comment]
Sofar I see no clue to understand the situation.
Please could you report (in a new issue report at the correct tracker) the snippet of syntax you use.
