### ISSUE TITLE
User/Remote_User error message when updating plugin.

### ISSUE THREAD

**Issue by jimmy-van** [splitbrain/dokuwiki-plugin-bureaucracy#132]
Following up from [issue #131](https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/issues/131), which was a user error - sysadmin had previously rolled back the bureaucracy plugin due to an error. We have since updated both, and remembered why we rolled back the bureaucracy plugin.

SysAdmin reports:
It seems to be buggy with following variable assignment not working:
 
> `$this->values['__user__'] = $INPUT->server->str('REMOTE_USER');`

and  the pagemod plugin works just fine, however the bureaucracy plugin has errors.

As before, this was manually downloaded and installed from:
https://www.dokuwiki.org/plugin:bureaucracy
https://www.dokuwiki.org/plugin:pagemod

**Comment by Klap-in** [comment]
Can you provide information, which enables me to reproduce your situation?

Examples of useful information: the snippet of syntax of a form that give the errors, the exact error messages, the authtype config setting value. etc etc

**Comment by jimmy-van** [comment]
Thanks for replying. I will tentatively close for now. After much digging, I think it's related to a conflict between the plugins and the underlying Dokuwiki release. It is being run on 2012-10-13 Adora Belle, and so this is the most likely cause.

I can't exactly test this theory yet (or upgrade the Wiki to resolve) because this is for an instance in Vanuatu, currently enduring [Tropical](https://twitter.com/hashtag/TCPam) [Cyclone](http://www.radionz.co.nz/international/pacific-news/268742/vanuatu-overwhelmed,-says-nz-foreign-minister) [Pam](http://edition.cnn.com/2015/03/15/asia/cyclone-pam-vanuatu/).

**Comment by campino2k** [comment]
I can support this to be reopened. Maybe that is related to using LDAP Auth, but the error message is that str() cannot be called on an Non-Object.

**Comment by Klap-in** [comment]
Please provide details which let me reproduce your situation:
- Dokuwiki version, version of plugins: data,sqlite, etc
- operation system/apache/other system info
- syntax you are using/page you are visiting
- copy of whole error, including the file occuring
- etc etc 
Thanks!

Are you sure you have updated everything to the latest version?

**Comment by campino2k** [comment]
Okay, I looked some time into this, an realized, that the wiki I was doing this in was not up to date and someone disabled the admin notifications for this :-/

After updating the wiki, everything is just fine. Thanks.
