### ISSUE TITLE
Honor plain text's line breaks

### ISSUE THREAD

**Issue by UXlibrarian** [splitbrain/dokuwiki-plugin-bureaucracy#138]
Is there a way to do this? I've been carefully setting up my wiki for weeks and today just discovered that my Bureaucracy backed forms does not recognize the plain text's line breaks. So I get all my text smashed together. I'm very disappointed, but am hopeful there's a fix for this.

**Comment by Klap-in** [comment]
Can you provide examples of the syntax that you were using? Please provide enough information that let us easily reproduce your case, thanks!

**Comment by Klap-in** [comment]
Without example of your form and template I have no clue were to search.
