### ISSUE TITLE
Sending email with addresses from hidden field in dependent fieldset

### ISSUE THREAD

**Issue by VeryBitter** [splitbrain/dokuwiki-plugin-bureaucracy#140]
Hi

I would like to send emails to addresses that depends on a selection. So I used fieldset dependency and hidden fields, as in the following code. Unfortunately it does not work and I get `"E-Mail address <@@addr@@> is not valid"` error code. It does work with the hidden field outside any dependent fieldset. 

What is surprising is that the hidden field in a dependent fieldset is passed on to the email body when I select a regular mail address (no placeholder) for the action field. More surprising, if I use the template action the hidden field, this time, is not passed on to the new page (see second code). Why does it work for email body and not page body?
Any hints would be very appreciated.

     <form>
     action mail @@addr@@

     select "Choice" "Toto|Tata"

     fieldset "Chosen" "Choice" "Toto"
     hidden "addr" "=toto@toto.fr"

     fieldset "Chosen" "Choice" "Tata"
     hidden "addr" "=tata@tata.fr"

     fieldset
     submit
     </form>
____
     <form>
     action   template "testpl" "test"

     select "Choice" "Toto|Tata"

     fieldset "Chosen" "Choice" "Toto"
     hidden "addr" "=toto@toto.fr"

     fieldset "Chosen" "Choice" "Tata"
     hidden "addr" "=tata@tata.fr"

     fieldset
     submit
     </form>

 testpl file

     @@addr@@

**Comment by Klap-in** [comment]
Strange, looking at source code suggests that placeholders should be replaced. 
I have to test this to see what is going on.

**Comment by Klap-in** [comment]
What happens if you use:
`action mail @@addr1@@ @@addr2@@`

With hidden fields with the labels `addr1` and `addr2` respectively.

**Comment by Klap-in** [comment]
- If field labels are use more times, the replacement pattern is overwritten by the last field. (can be seen by choicing 'Tata' in your example.
- If a field is not set (e.g. because the fieldset was hidden) the placeholder is not replace by a value. If you prefer an empty string when empty, you could add `|` without further text. Now the placeholder is replaced by empty string, if the field is not set/hidden.
```
 <form>
 action mail @@addr1|@@@@addr2|@@

 select "Choice" "Toto|Tata"

 fieldset "Chosen" "Choice" "Toto"
 hidden "addr1" "=toto@toto.fr"

 fieldset "Chosen" "Choice" "Tata"
 hidden "addr2" "=tata@tata.fr"

 fieldset
 submit
 </form>
```
