### ISSUE TITLE
Syntax for mailfrom

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-bureaucracy#147]
Hi,

for the mail mode of the Bureaucracy Plugin I am searching for the syntax to set the mailfrom parameter. Though in the https://github.com/splitbrain/dokuwiki-plugin-bureaucracy/issues/17 is described that this can be realized, I don't find any description how to set this value.

Regards
Juergen

**Comment by Klap-in** [comment]
Mailfrom is default senders email of your wiki, and cannot be changed.

You could set reply-to addresses by adding `@@` to `email` fields.

**Comment by Klap-in** [comment]
Mail From will not be supported. Use ReplyTo instead.
