### ISSUE TITLE
Use a placeholder to switch between templates does not work as expected

### ISSUE THREAD

**Issue by duenni** [splitbrain/dokuwiki-plugin-bureaucracy#151]
Hi there,

I try to use a hidden field to switch between two templates.

Form:
```
<form>
action template @@templateswitcher@@ otherns:

fieldset "New Page"
textbox  "Pagename" @
textbox  "Photo" "=noimage.jpg" !
hidden "templateswitcher" "=myns:template1pic"

yesno    "Another Picture?"
fieldset "Another Picture" "Another Picture?"
textbox  "Photo 2" "=noimage2.jpg" !
hidden "templateswitcher" "=myns:template2pics"
.
.
.
submit
```
Template 1 located at myns:template1pic:
```
===== @@Pagename@@ =====
{{:otherns:@@Photo@@?100|@@Pagename@@ Pic 1}}
.
.
.
```
Template 2 located at myns:template2pics
```
===== @@Pagename@@ =====
{{:otherns:@@Photo@@?100|@@Pagename@@ Pic 1}}
{{:otherns:@@Photo 2@@?100|@@Pagename@@ Pic 2}}
.
.
.
```

This will only work when clicking the yesno box otherwise I get `Could not read template. Maybe it doesn't exist or you have no read permissions?`
Thanks in advance for looking into this!

**Comment by Klap-in** [comment]
You have a duplicated field label. The value of the last field is always used. 

A tric is to use:
`@@fieldlabel|@@`
If the field is set, the field value is used. If not(or hidden), it is the value after `|`. What is an empty string here. 

Now you could combine some placeholders.

**Comment by duenni** [comment]
```
<form>
action template @@templateswitcher|myns:template1pic@@ otherns:
...
yesno    "Another Picture?"
fieldset "Another Picture" "Another Picture?"
textbox  "Photo 2" "=noimage2.jpg" !
hidden "templateswitcher" "=myns:template2pics"
```
First `hidden` field can be omitted. 
It works!
Thanks for the tip and the quick response! Really appreciate it!

**Comment by Klap-in** [comment]
Thanks, you are welcome!
