### ISSUE TITLE
use placeholders for pagemod_id in action pagemod

### ISSUE THREAD

**Issue by BD2k1** [splitbrain/dokuwiki-plugin-bureaucracy#183]
Hi,

I want to use the result of a select field as a pagemod_id. I have two wiki pages. One containing the form and one that has to be modified. The pages that has to be modified contains several pagemod entries each with a unique pagemod id. Choosing an entry from a select field shall be used as a pagemod id.
Therefore I tried to use a placeholder @@selectfield@@ since it works with the action template. It does not work with pagemod...

It would be nice to have that possibility. Other workarounds are appreciated.

Please let me know if this is a pagemod issue. I will open an issue there.

**Comment by Klap-in** [comment]
This requires an update of the action pagemod of the pagemod plugin, so please file the issue there please.

But I expect the approach could be quite similar as already applied for the template action.

**Comment by Klap-in** [comment]
Similar request: https://github.com/BaselineIT/dokuwiki-pagemod/issues/20

**Comment by Klap-in** [comment]
Hi, I opened a pull request with a solution.
