### ISSUE TITLE
Checkboxes in dependant fieldsets don't transfer contents into templates

### ISSUE THREAD

**Issue by SFITCS** [splitbrain/dokuwiki-plugin-bureaucracy#186]
Tested with latest stable Bureaucracy and DokuWiki. Plugins installed are latest versions of acl, authpdo, authplain, bureaucracy, comment, config, extension, info, popularity, revert, styling, upgrade, usermanager.

```
<form>
action template _ hardware:@@HardwareType@@:"@@Hardware Name@@:start"
Select "HardwareType" "Computers|Modems|Phones|Printers|Scanners"
YesNo "Test" "=Yes" "!No"
Fieldset "OS Support" "HardwareType" "Modems"
YesNo "OSX Support" "=Yes" "!No"
Fieldset
Submit "Create a New record"
</form>

```

Template:-
```
====== @@Hardware Name@@ ======

Test = @@Test@@

OSX Support = @@OSX Support@@
```

Result (if **Modems** is selected as **HardwareType**):-

**====== Roadster ======**

**Test = Yes**

**OSX Support = @@OSX Support@@**

**Comment by Klap-in** [comment]
For selecting other options than 'Modems' I got the following line in the generated page:
`OSX Support = @@OSX Support@@`

and when selecting Modems I got:
`OSX Support = Yes`
or 
`OSX Support = No`

So it works as intended, it is not? Did you have same spelling as above?

**Comment by SFITCS** [comment]
Yes - it works. [shame-faced] I failed to properly isolate the problem - the issue seems to be with the Structured Data Plugin.
My apologies for wasting your time. Thank you for the prompt response, and your work.
