### ISSUE TITLE
File Upload in Documents

### ISSUE THREAD

**Issue by pdohmen91** [splitbrain/dokuwiki-plugin-bureaucracy#189]
I would like to use a file input in a form and it should be sent as an attachment via email.

In your Documentation is a "Fix me". Do you already know when this will be working again?
I tried it but it did not work for me now.

Thanks!

**Comment by Klap-in** [comment]
I guess the fixme is about the lack of documentation. 

Do you test if it is working for you?

**Comment by lisps** [comment]
I had a issue on sending images as attachement. I fixed it by embeding images into the email.
forgot to make a pull request - will do this soon

**Comment by pdohmen91** [comment]
Yes I added it to the form but it did not attach the file to the created email.

But I am not sure how it has to be configured. Do I need to configure it only in the form or also in the template which I am using for the email?

**Comment by Klap-in** [comment]
I have at the moment not an installation with proper mail sending configured, so difficult to test.

But looking at code I see the uploaded file should be attached to an email. Can you share the syntax of a simplified bureaucracy form which shows this issue for you?

**Comment by pdohmen91** [comment]
As I have written I am not sure if I have to add something to my Email Template to get the files attached to the created email.

**Form:**
====== Create new Ticket ======
<form>
Action mail xx@xx.xx
usemailtemplate general:mailtemplate
Subject "Customer Issue | @@Subject@@"
Thanks "Thanks for submitting your valuable data. The issue will be sent to our ticketing system and will be answered as soon as possible."

Fieldset "Customer Information"
Textbox  "Name" "=Your Name"
email "Your E-Mail Address"
Textbox "User Name" !

fieldset "Main Information"
select "Category" "General|Login|Job|Phrase|Question Lists|APL|Backup Function"
Textbox "Subject"
Textbox "Job Id" !
Textbox "Url" !

fieldset "Backup Function" "Category" "Backup Function"
Textbox "The other username" !
select "Who is backup?" "I am the backup person|The other is the backup person" !

fieldset "Issue"
textarea "Issue description"
file "Documents"
submit "Create Ticket"
</form>

**Email Template:**
======Mail template page======

<code html>
Send from DokuWiki User:
User: @USER@
Mail: @MAIL@
On: @DAY@.@MONTH@.@YEAR@ @TIME@

User Information:
Name: @@Name@@
EMail: @@Your E-Mail Address@@
Wave Username: @@User Name@@

Customer Information:
Customer: @@Customer@@
Mandant: @@Mandant|N/A@@

Main Information:
Category: @@Category@@
Subject: @@Subject@@
URL: @@Url|N/A@@
Wave Job Id: @@Job Id@@

Backup Function:
The other username: @@The other username|Not given@@
Who is backup?: @@Who is backup?@@

Description:
@@Issue description@@
</code>


<code text>
Send from DokuWiki User:
User: @USER@
Mail: @MAIL@
On: @DAY@.@MONTH@.@YEAR@ @TIME@

User Information:
Name: @@Name@@
EMail: @@Your E-Mail Address@@
Wave Username: @@User Name@@

Customer Information:
Customer: @@Customer@@
Mandant: @@Mandant|N/A@@

Main Information:
Category: @@Category@@
Subject: @@Subject@@
URL: @@Url|N/A@@
Wave Job Id: @@Job Id@@

Backup Function:
The other username: @@The other username|Not given@@
Who is backup?: @@Who is backup?@@

Description:
@@Issue description@@
</code>

**Comment by Klap-in** [comment]
Attaching files to mail should be independent whether you use an email template.

Could you test once what happens if you don't use the `usemailtemplate` field?
I expect, reading the code that it should not change anything, but maybe I missed something..

**Comment by pdohmen91** [comment]
No change. Unfortunately I cannot give you access to the wiki since it is not reachable from outside of our network here.

I´m not sure which information I could give you to find an issue in my configuration. I´m far away from being a Wiki expert.
For sending mails I am using the swiftmail plugin.

**Comment by Klap-in** [comment]
I got the impression from the Swiftmail plugin's wiki page, that it doesn't support attachment...
At that wiki page you are recommendated to use the SMTP plugin.. So maybe that is worth a try.

**Comment by pdohmen91** [comment]
That's it! Thanks for your help!
