### ISSUE TITLE
Double quotes not required for translation field in labels page

### ISSUE THREAD

**Issue by SFITCS** [splitbrain/dokuwiki-plugin-bureaucracy#195]
# Non-issue
Translation field work fine _without_ any quotes surrounding them.
At most this is a minor documentation error.
I'd call it an undocumented convenience (saves typing).  :)

**Comment by Klap-in** [comment]
This is documented at the wiki page, just above the Fields section 
https://www.dokuwiki.org/plugin:bureaucracy#fields

Default the quotes are used in the examples to prevent confusion for people learning the syntax.

**Comment by SFITCS** [comment]
On 16/12/16 09:38, Gerrit Uitslag wrote:
>
> This is documented at the wiki page, just above the Fields section
> https://www.dokuwiki.org/plugin:bureaucracy#fields
>

If you mean /Arguments need to be wrapped in double quotes when they
contain spaces e.g. //|"S p a c e s"|/,  then yes.
I suspect it would be clearer if it was /Arguments *only* need to be
wrapped in double quotes when they contain spaces e.g. //|"S p a c e s"|/
[shrug]
