### ISSUE TITLE
Documentation for new "script" action

### ISSUE THREAD

**Issue by dregad** [splitbrain/dokuwiki-plugin-bureaucracy#218]
The new _script_ action introduced in #209 / 2017-07-27 release looks promising, but the documentation available at https://www.dokuwiki.org/plugin:bureaucracy#script_mode is sorely lacking.

It would be great if more detailed docs could be provided, maybe with some sample usage.

**Comment by Klap-in** [comment]
@micgro42 could you write these docs please?

**Comment by micgro42** [comment]
I linked the interface that has to be implemented and added an example script, that just logs the values of the parameters to DokuWiki's debug logs.

What else would be expected as documentation?

**Comment by dregad** [comment]
That's pretty good, thanks !

Between opening this issue and now, I spent some time trying to figure things out, and at the end of the day it was not as complex as I thought upon reading the doc. 

I took the liberty of updating your example with a corresponding form and shortening the handler's PHPDoc comment.
