### ISSUE TITLE
plugin is not on translate.dokuwiki.org

### ISSUE THREAD

**Issue by schplurtz** [splitbrain/dokuwiki-plugin-bureaucracy#230]
Hi, I just noticed that `Max size of mail attachments in Bytes. (per File)` has no French translation.

I went to translate.dokuwiki.org and did not find this plugin.

Could you add it to translate.dokuwiki.org ?

Schplurtz

**Comment by splitbrain** [comment]
https://translate.dokuwiki.org/plugin/bureaucracy
