### ISSUE TITLE
Template action ignores template name and breaks existing forms

### ISSUE THREAD

**Issue by psy-q** [splitbrain/dokuwiki-plugin-bureaucracy#235]
I've upgraded to 2018-01-08 and this seems to have broken all my template-based forms. I have a form like this on the page protokolle:start (sorry about the German, I tried to use a real example and only shortened the list of templates):

```
<form>
fieldset "Neues Protokoll erstellen"
action template templates:@@Vorlage@@ protokolle: "_"
thanks    "Protokoll wurde erstellt und kann gefüllt werden"
 
static "Bitte die teilnehmenden Gruppen, Vorlage, und Datum der Sitzung wählen:"
struct_field "protokolle.groups"
 
select "Vorlage" "protokolle|protokoll_abteilungssitzung|protokoll_entwicklung" @
struct_field "protokolle.date" @
 
submit
</form>
```
When submitting the form it will *not* use e.g. templates:protokoll_entwicklung even if that is selected in the dropdown "Vorlage". Instead, it will always simply use the name of the current page the form is residing on, e.g. protokolle:start in this example. The result is an error, of course, because this makes no sense:

> Could not read template "protokolle:start". Maybe it doesn't exist or you have no read permissions?

It feels as if it substitutes `@ID@` instead of whatever template name I give. I can also set up the example from the docs which is:

```
action   template userstpl users: :
```
But it fails in the same way and tries to use `protokolle:start` instead of `userstpl`.

Downgrading to 2017-10-13 fixes the issue.

**Comment by micgro42** [comment]
Hey @psy-q, could you try the current release of bureaucracy to see if this is still broken for you?

**Comment by psy-q** [comment]
I'll be able to verify that in about 2 - 3 weeks, I hope that's not too late :(

**Comment by psy-q** [comment]
OK, I did indeed get to test it in time :)
I've tested version 2018-07-06 and it works fine, so closing this. Thank you!
