### ISSUE TITLE
On action template: placeholder for yesno field not filled with user provided values 

### ISSUE THREAD

**Issue by umbomas** [splitbrain/dokuwiki-plugin-bureaucracy#237]
If I create a new page using the action template, any "yesno" field in the generated page is always rendered as '0' or '1' according to the selection in the Bureaucracy form. 
The so-called "default values for yes and no" (see https://www.dokuwiki.org/plugin:bureaucracy) are ignored.

The yesno field is correctly handled in the previous version of the plugin (2017-10-13).

_My configuration: Dokuwiki on a Stick on Windows._

**Test page:**
```
====== bureaucracy yesno bug ======

<form>
action template yesno_bug_tpl .:yesno_bug_output

thanks "Check the test result"

textbox "a_text"
select "a_list" "|alfa|bravo|charlie"
yesno "yes_or_no" "=Yes" "!No"
yesno "no_user_provided_values"
submit
</form>
```

**Template for the test page:**
```
====== yesno bug output ======

These are the provided values

| textbox "a_text"  | @@a_text@@  |
| select "a_list"  | @@a_list@@  |
| yesno "yes_or_no"  | @@yes_or_no@@  |
| yesno "no_user_provided_values"  | @@no_user_provided_values@@  |
```

**Comment by umbomas** [comment]
Pull request #234 **yesno replacement bugfix** solves the issue, please accept it.

**Comment by dregad** [comment]
#234 has been merged, this should be closed.
