### ISSUE TITLE
functionality broken (after upgrade?)

### ISSUE THREAD

**Issue by asheenlevrai** [splitbrain/dokuwiki-plugin-bureaucracy#245]
Hi,

We have been using this plugin for several years now in order to manage lists of items (antibodies) in our research lab. For some reason the form we created doesn't work properly anymore (it worked perfectly in the past). New entries don't adopt the appropriate format. I suspect this is due to an update since we constantly update DW and its plugins.

It seems like the problem appeared around December 2017. The issue is that new entries generate a new namespace rather than a new wiki page. And obviously the data is a bit messed up...

Here is the form we use and the 2 different lists we generate from the entries that the form generates. Please let me know how to fix this issue or how to troubleshoot it.
```
<form>
Action template antibodies:irlab_"@@Antibody Type@@_antibody_template" "antibodies:@@Host@@_anti-@@Target Species|@@@@Target Prot|@@_@@Revelation Agent|@@_ref-@@Reference@@)"
Thanks    "[[irlab_antibody_list|Reload antibody list]]"
 
Fieldset   "New Antibody"
Select     "Antibody Type" "Please Choose:|Primary|Secondary" /^[^\:]+$/ "**Choose AB type"
Select     "Host" "Please enter here the species in which the antibody was raised:|Chicken|Donkey|Goat|Guinea Pig|Mouse|Rabbit|Rat|Sheep" /^[^\/:;]+$/ "**Choose host species"
Textbox    "Target Species" /^[^\/:;]+$/ "**please do not use ''/'', '':'' or '';''" !
Static     "FOR TARGET SPECIES: See instructions in the next section (below):"
Static     "Please check the following if this antibody is discontinued, aspecific or was tested and doesn't work at all. Please also add comments in ''Remarks''"
Yesno      "Do Not Use This Antibody"


Fieldset   "Primary Antibody" "Antibody Type" "Primary"
Static     "FOR TARGET SPECIES (previous section): use coma if multiple species are mentioned. For instance if an anti-ProteinX antibody binds both the human and murine form of ProteinX, please mention ''Human, mouse'', for instance. Leave blank if you don't know"
Textbox    "Target Prot" "=e.g: ''X'' for anti-X antibodies" /^[^\/,:;]+$/ "**please do not use ''/'', '','', '':'' or '';''"

Fieldset   "Secondary Antibody" "Antibody Type" "Secondary"
Static     "FOR TARGET SPECIES (previous section): use for instance ''goat'' for anti-goat secondaries or ''rabbit'' for anti-rabbit secondaries"
Textbox    "Revelation Agent" "=Fluorophore or Enzyme used to reveal signal:" /^[^\/,:;]+$/ "**please do not use ''/'', '','', '':'' or '';''"


Fieldset   "Additional Information"
Select     "Storage Location" "Please Choose:|fridge (4°)|freezer (-20°)" /^[^\:]+$/ "**Choose location"
number     "Storage Position" "=Add here the number corresponding to the next AVAILABLE space in the fridge/freezer" 000
Textbox    "Provider" /^[^\/:;]+$/ "**please do not use ''/'', '':'' or '';''"
Textbox    "Reference" "=''/'', '';'' and '':'' not allowed, remove any and specify the proper reference in ''Remarks'' (below) if necessary" /^[^\/,:;]+$/ "**'/'', '';'' and '':'' not allowed, remove any and specify the proper reference in ''Remarks'' (below) if necessary"
Textarea   "Remarks" x3 !


Fieldset    "Issue" "Do Not Use This Antibody"
Hidden      "Obsolete" "=Do Not Use" !
Static      "This antibody has been marked as being discontinued, aspecific or not working"


Fieldset   "Add to IRlab list"
Submit     "Add Antibody"
</form>

===== Primary Antibodies =====

Use the dynamic filters (1<sup>st</sup> line of blank fields) to filter the list and find primary antibodies easily

---- datatable primaryAntibody ----
cols       :  %pageid%, Host Species_, Target Prot, Target Speciess, Storage Position, Storage Location, Provider, Reference, Remarks_, Obsolete
headers    : Edit Link, Host, Target (Prot.), Target (Species), Storage Position, Storage, Provider, Reference, Remarks, Warning
sort       : Obsolete
filter     : %class%= primary antibody
filter     : Storage Position != @@Storage Position@@
dynfilters : 1
----

===== Secondary Antibodies =====

Use the dynamic filters (1<sup>st</sup> line of blank fields) to filter the list and find secondary antibodies easily.

---- datatable secondaryAntibody ----
cols       :  %pageid%, Host Species_, Target Speciess, Revelation Agent, Storage Position, Storage Location, Provider, Reference, Remarks_, Obsolete
headers    : Edit Link, Host, Target Species, Revelation Agent, Storage Position, Storage, Provider, Reference, Remarks, Warning
sort       : Obsolete
filter     : %class%=secondary antibody
filter     : Storage Position != @@Storage Position@@
dynfilters : 1
----

```

Thank you very much in advance for your help.

Best,
-a-

**Comment by asheenlevrai** [comment]
![template](https://user-images.githubusercontent.com/5127613/38931697-59c72a1e-4314-11e8-9f4d-1a8ff584fd7e.JPG)


templates are pages in the antibodies namespace

**Comment by asheenlevrai** [comment]
I made the following modification:
Textbox    "Revelation Agent" /^[^\/,:;]+$/ "**please do not use ''/'', '','', '':'' or '';''"
Static     "REVELATION AGENT: Fluorophore or Enzyme used to reveal signal. PLEASE USE THE SAME NOMENCLATURE AS WHAT IS ALREADY PRESENT IN THE LIST"

I guess the default message for Revelation Agent" was problematic since it generated a default value for this field (Textbox    "Revelation Agent" "=Fluorophore or Enzyme used to reveal signal:" /^[^\/,:;]+$/ "**please do not use ''/'', '','', '':'' or '';''"
)

**Comment by Klap-in** [comment]
I guess that before the `e.g:` has created namespaced links. But in current form the form don't allows this input. So that should not be an issue any more.

So far I have no other clues.

(my previous question was feeded by one of the features of the plugin. The plugin can copy an entire namespace as template instead of one page. But it looks like that is not happening here. The first glance at the urls in the pictures above suggest that the namespaces are happening because the targetpagename that was built did contains semicolons...)

Could you describe an example of values that you fill in the form that trigger this behaviour?
Because so far I could not reproduce the case.

**Comment by Klap-in** [comment]
The default value `"=Fluorophore or Enzyme used to reveal signal:"` contains a semicolon on the end. Does it helps if you remove it?

**Comment by asheenlevrai** [comment]
I need the semicolon as far as I understand. It is to use what is called "nice alternative" in the doc. 

Otherwise I get an error message when people create new PRIMARY antibody (thus leaving the Revelation Agent field empty).

**Comment by asheenlevrai** [comment]
I now moved all the "hints" that introduced as default values for Revelation Agent and Target Prot to Static fields... It looks less good but it works...

**Comment by asheenlevrai** [comment]
I now have one last issue... No matter if the checkbox is checked or not the value is "Do Not Use"... while it should not (only if the checkbox is checked)...

**Comment by asheenlevrai** [comment]
I will open a thread on the support forum. this one can be closed. Sorry for the inconvenience since the problem came from our end. Thanks a lot to Klap-in for your help.

**Comment by Klap-in** [comment]
btw, with semicolon I mean `:`, not the vertical line `|`.

For yesno you need to provide the default values. These are used in the placeholder (so far I remember), otherwise there is no value available to use in the placeholder.

```
yesno
- creates a checkbox
- needs a label
- needs default values for yes and no ( =true_value !false_value )
```

**Comment by asheenlevrai** [comment]
Thanks. I saw the thing about the default values. However, it used to work like that in the past. Was this changed in a recent update of the plugin.
I don't know how to implement this in our form. For now it goes like this (not working properly):
...
Yesno      "Do Not Use This Antibody"
...

...
Fieldset    "Issue" "Do Not Use This Antibody"
Hidden      "Obsolete" "=Do Not Use" "!"
Static      "This antibody has been marked as being discontinued, aspecific or not working"
...

Best,
-a-

**Comment by asheenlevrai** [comment]
"The default value "=Fluorophore or Enzyme used to reveal signal:" contains a semicolon on the end. Does it helps if you remove it?"

Yes! if works this way :) Thank you!

**Comment by asheenlevrai** [comment]
I will need some time to look into that.

I think I needed the field to be optional since in most cases the value for OBSOLETE is empty.

**Comment by asheenlevrai** [comment]
OBSOLETE is a _type alias_ and the only valid value is "Do not use". Hence the requirement for the field to be optional?

**Comment by asheenlevrai** [comment]
Actually I double checked and the field obsolete is not optional. What field were you referring to when you said it was marked as optional?

**Comment by asheenlevrai** [comment]
the doc mentions the following for yesno checkboxes:
When a fieldset refers to a yesno field, no third argument is needed, instead it checks if the yesno is set. No default values are required for yesno where the fieldset depends on, unless you like a return value to your mail or template from that yesno field of course.

**Comment by Klap-in** [comment]
Yes I expect it is working as you told. But I haven't tested.
What I mentioned before was an alternative approach for using `yesno` instead of the `hidden` field. This approach should work.

Sorry for the confusion.

Are there still questions remaining?
If so, could you post the last version of your form as well?

**Comment by asheenlevrai** [comment]
Yes the last remaining issue is that all newly generated antibodies are marked as Do Not Use even when the yesno box is not checked in the form. It seems like the hidden filed is set to Do Not Use no matter what, there is no dependency on the yesno box.

Can you re-explain your alteernative method? I'm not sure I understand where I should put the placeholder.

Here is the current version of the form:

===== Primary Antibodies =====

---- datatable primaryAntibody ----
cols       :  %pageid%, Host Species_, Target Prot, Target Speciess, Storage Position, Storage Location, Provider, Reference, Remarks_, Obsolete
headers    : Edit Link, Host, Target (Prot.), Target (Species), Storage Position, Storage, Provider, Reference, Remarks, Warning
sort       : Obsolete
filter     : %class%= primary antibody
filter     : Storage Position != @@Storage Position@@
dynfilters : 1
----

===== Secondary Antibodies =====

---- datatable secondaryAntibody ----
cols       :  %pageid%, Host Species_, Target Speciess, Revelation Agent, Storage Position, Storage Location, Provider, Reference, Remarks_, Obsolete
headers    : Edit Link, Host, Target Species, Revelation Agent, Storage Position, Storage, Provider, Reference, Remarks, Warning
sort       : Obsolete
filter     : %class%=secondary antibody
filter     : Storage Position != @@Storage Position@@
dynfilters : 1
----

----
====== Add a new antibody ======


Last **OCCUPIED** space in the **__fridge__** (4°):
---- datalist tubeFridge ----
cols     : Storage Position
sort     : ^Storage Position
filter   : Storage Location=fridge (4°)
max      :1
----

Last **OCCUPIED** space in the **__freezer__** (-20°):
---- datalist tubeFreezer ----
cols     : Storage Position
sort     : ^Storage Position
filter   : Storage Location=freezer (-20°)
max      :1
----


<form>
Action template antibodies:irlab_"@@Antibody Type@@_antibody_template" "antibodies:@@Host@@_anti-@@Target Species|@@@@Target Prot|@@_@@Revelation Agent|@@_ref-@@Reference@@)"
Thanks    "[[irlab_antibody_list|Reload antibody list]]"
 
Fieldset   "New Antibody"
Select     "Antibody Type" "Please Choose:|Primary|Secondary" /^[^\:]+$/ "**Choose AB type"
Select     "Host" "Please enter here the species in which the antibody was raised:|Chicken|Donkey|Goat|Guinea pig|Mouse|Rabbit|Rat|Sheep" /^[^\/:;]+$/ "**Choose host species"
Textbox    "Target Species" /^[^\/:;]+$/ "**please do not use ''/'', '':'' or '';''" !
Static     "FOR TARGET SPECIES: See instructions in the next section (below):"
Static     "Please check the following if this antibody is discontinued, aspecific or was tested and doesn't work at all. Please also add comments in ''Remarks''"
Yesno      "Do Not Use This Antibody"


Fieldset   "Primary Antibody" "Antibody Type" "Primary"
Static     "FOR TARGET SPECIES (previous section): use coma if multiple species are mentioned. For instance if an anti-ProteinX antibody binds both the human and murine form of ProteinX, please mention ''Human, mouse'', for instance. Leave blank if you don't know"
Textbox    "Target Prot" /^[^\/,:;]+$/ "**please do not use ''/'', '','', '':'' or '';''"
Static     "FOR TARGET PROT: don't add anti -> e.g: add only ''X'' for anti-X antibodies"

Fieldset   "Secondary Antibody" "Antibody Type" "Secondary"
Static     "FOR TARGET SPECIES (previous section): use for instance ''goat'' for anti-goat secondaries or ''rabbit'' for anti-rabbit secondaries"
Textbox    "Revelation Agent" /^[^\/,:;]+$/ "**please do not use ''/'', '','', '':'' or '';''"
Static     "REVELATION AGENT: Fluorophore or Enzyme used to reveal signal. PLEASE USE THE SAME NOMENCLATURE AS WHAT IS ALREADY PRESENT IN THE LIST"


Fieldset   "Additional Information"
Select     "Storage Location" "Please Choose:|fridge (4°)|freezer (-20°)" /^[^\:]+$/ "**Choose location"
number     "Storage Position" "=Add here the number corresponding to the next AVAILABLE space in the fridge/freezer" 000
Textbox    "Provider" /^[^\/:;]+$/ "**please do not use ''/'', '':'' or '';''"
Textbox    "Reference" "=''/'', '';'' and '':'' not allowed, remove any and specify the proper reference in ''Remarks'' (below) if necessary" /^[^\/,:;]+$/ "**'/'', '';'' and '':'' not allowed, remove any and specify the proper reference in ''Remarks'' (below) if necessary"
Textarea   "Remarks" x3 !


Fieldset    "Issue" "Do Not Use This Antibody"
Hidden      "Obsolete" "=Do Not Use"
Static      "This antibody has been marked as being discontinued, aspecific or not working"


Fieldset   "Add to IRlab list"
Submit     "Add Antibody"
</form

**Comment by asheenlevrai** [comment]
![obsolete](https://user-images.githubusercontent.com/5127613/39176434-1ac91514-47ad-11e8-839d-4aa2fa969820.JPG)

**Comment by Klap-in** [comment]
I will try to do some tests this evening. 
What are the placeholders you are using in your templates?

**Comment by Klap-in** [comment]
For me is your setup working, such as you paste above.
I have no idea what could be a difference between your and my setup...

----
Explanation of the alternative:
In template replace:
```
Obsolete_obsolete                  : @@Obsolete|@@ # Set to 'Do Not Use' if this antibody is discontinued, aspecific or proved not to work. Please add comments in the 'Remarks' field
```
by:
```
Obsolete_obsolete                  : @@Do Not Use This Antibody|@@ # Set to 'Do Not Use' if this antibody is discontinued, aspecific or proved not to work. Please add comments in the 'Remarks' field
```

And in the form replace:
```
Yesno      "Do Not Use This Antibody"
```
by:
```
Yesno      "Do Not Use This Antibody" "=Do Not Use"
```

**Comment by asheenlevrai** [comment]
Thanks :)

You don't get all newly created antibodies marked as "Do Not Use", no matter what?

**Comment by asheenlevrai** [comment]
I tried your alternative but now I get the opposite effect. New entries don't get the "Do Not Use" even when the checkbox is checked in the form.
Should I modify the OBSOLETE type alias in anyway (see upstream post)?

Tx
-a-

**Comment by Klap-in** [comment]
So far no idea what could happen...

Maybe useful to test if the behaviour is different if you empty temporary the 'Valid values' in the admin?

**Comment by asheenlevrai** [comment]
but if I do this nothing will be considered a valid value?

**Comment by Klap-in** [comment]
if it is empty, every value is acceptable.

So far I know this 'Valid values' has limit purpose. So I would not expect it influences the bureaucracy form. (but I also don't know everything about this plugin, therefore I asked that you test it.)

**Comment by asheenlevrai** [comment]
The documentation of the plugin mentions:

> NOTE: 
> Apparently dependencies don't work when the choice is provided by “radio” (only “select” and “yesno” work) for some reason. There might by a logical explanation for this, maybe

I thought maybe there is also a problem with yesno (not only radio). Using Select indeed solves the issue.

I guess someone should edit the documentation to mention that yesno doesn't work anymore for dependencies (should I do it myself?).

I believe it would be interesting to check the old code of the plugin to see why the ability to use yesno for dependencies has been lost (probably a bug).

**Comment by Klap-in** [comment]
hmmm. bit strange. In my setup it seems to work fine. So maybe there is more going on?

Let see if I can come up with some test cases to check these stuff.

**Comment by asheenlevrai** [comment]
Thanks.
Let me know what you want me to test :)
