### ISSUE TITLE
Error when create new page and new entry with Bureaucracy form with Struct

### ISSUE THREAD

**Issue by Digitalin** [splitbrain/dokuwiki-plugin-bureaucracy#246]
After months using this config without problems (last creation by 17/04), I meet same issue in production and locally : 

`«Template "ca:adher:form:addher" not found. It does not exist or you do not have read permission.`

**Apache/error.log**
```
PHP Warning:  preg_replace(): Parameter mismatch, pattern is a 
string while replacement is an array in /../../plugins/bureaucracy/syntax.php 
on line 475, referer: http://../doku.php/ca/adher/form/addher
```
The page addher exists and it is the form from which to create new page and new entry in Struct. As I have two organizations on this wiki, I meet exactly the same problem (effect and error) in another namespace with others schemas, template...

I have no clue about. However, it seems it is a Bureaucracy issue because it works manually (without the form).   Some details :
PHP : 5.6
Apache 2.4.7
DokuWiki : Frusterick Manners
Bootstrap3 : 2018-02-16
Sqlite : 2018-03-27
Bureaucracy : 2018-03-28
Struct : 2018-04-24
do=check : nothing relevant
have tried to reinstall plugins Sqlite, Struct, Bureaucracy : same
PHP display_errors gives the same message mulitple time than apache

Struct schema **infos** assigned to **ca:adher:infos:***
allowed editors : @user
ACL : Ok

**addher** 

```
===== Formulaire de création d'un nouvel adhérent dans la gestion =====
<form>
Action template templates:adher_tpl ca:adher:infos:@@login@@ :
textbox "login"
struct_schema "infos" !
submit "Ajouter un nouvel adhérent" !
</form>
```

**adher_tpl** 
```
[[ca:adher:infos|retour]]\\
Créé par @USER@ le @DATE@

===== Page adhérent @PAGE@ =====
```

**Comment by Digitalin** [comment]
Hi,
I don't know if the last release (2018-05-17 23:50) was about this issue but just in case, this release doesn't fix it unfortunately.

**Comment by micgro42** [comment]
Hey @Digitalin, could you try the current release of bureaucracy to see if this is still broken for you?

**Comment by Digitalin** [comment]
Hey, 
With the last release of Bureaucracy (2018-07-06) tested with Struct (2018-07-07), all works well.
I think bug has been fixed now. Thanks.
