### ISSUE TITLE
Current version no longer compatible with php 5.6.30?

### ISSUE THREAD

**Issue by virk** [splitbrain/dokuwiki-plugin-bureaucracy#301]
When I updated bureaucracy to current version I got a blank screen. Switching back to old version 2021-02-17 (via TimeMachine) solved this problem.
Can somebody confirm, that the current version is no longer compatible with php 5.6.30?

**Comment by virk** [comment]
Can anybody else confirm that current version does not work with php 5.6.30?

**Comment by Klap-in** [comment]
Duplicate of #294
