### ISSUE TITLE
Feature request: link mode

### ISSUE THREAD

**Issue by Chris75forumname** [splitbrain/dokuwiki-plugin-bureaucracy#306]
Hi,
there is template mode, which creates a new page, then there is email mode, which sends an email. And I miss the link mode, where the user input is used to create a link, which is opened/redirected after submit.
Cheers!

**Comment by splitbrain** [comment]
What does "create a link" mean? What exactly is it you want?

**Comment by Chris75forumname** [comment]
In essence, in link mode, bureaucracy would use (similar to email mode) a link template and write a link page and in the end execute the assembled link. Yours, Chris

**Comment by Chris75forumname** [comment]
Okay, I found a workaround now, with the above mentioned `thanks __redirect__` hack and some jquery that opens the created link on the created page, automatically. Thanks for your time!
