### ISSUE TITLE
Use of deprecated functions in IGOR

### ISSUE THREAD

**Issue by LMS235** [splitbrain/dokuwiki-plugin-bureaucracy#308]
After Upgrade to Igor:

2022-08-01 08:39:06
utf8_ucfirst() is deprecated. It was called from syntax_plugin_bureaucracy::prepareNamespacetemplateReplacements() in <xxx>/wiki/lib/plugins/bureaucracy/syntax.php:583 dokuwiki\Utf8\PhpString::ucfirst() should be used instead!
2022-08-01 08:39:06
utf8_strtoupper() is deprecated. It was called from syntax_plugin_bureaucracy::prepareNamespacetemplateReplacements() in <xxx>/wiki/lib/plugins/bureaucracy/syntax.php:584 dokuwiki\Utf8\PhpString::strtoupper() should be used instead!
2022-08-01 08:39:06
utf8_ucfirst() is deprecated. It was called from syntax_plugin_bureaucracy::prepareNamespacetemplateReplacements() in <xxx>/wiki/lib/plugins/bureaucracy/syntax.php:586 dokuwiki\Utf8\PhpString::ucfirst() should be used instead!
2022-08-01 08:39:06
utf8_ucwords() is deprecated. It was called from syntax_plugin_bureaucracy::prepareNamespacetemplateReplacements() in <xxx>/wiki/lib/plugins/bureaucracy/syntax.php:587 dokuwiki\Utf8\PhpString::ucwords() should be used instead!
2022-08-01 08:39:06
utf8_strtoupper() is deprecated. It was called from syntax_plugin_bureaucracy::prepareNamespacetemplateReplacements() in <xxx>/wiki/lib/plugins/bureaucracy/syntax.php:588 dokuwiki\Utf8\PhpString::strtoupper() should be used instead!

**Comment by HMJR** [comment]
Same problem after update to Release 2023-04-04 "Jack Jackrum", with last update of the plugin installed. PHP 8,1.
Can some explain to us what causes this messages?

**Comment by dregad** [comment]
This is fixed in PR #/317
