### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by eilko** [splitbrain/dokuwiki-plugin-bureaucracy#323]
Last week I have updated my site to  **latest dokuwiki/latest plugin/php 8.2**

I have installed the captcha plugin and made a form at https://www.altaplana.be/en/community/contact
The captcha code is added under the form. But I can submit the form without the captcha code being entered.  (Feel free to test on the site).   

Since the upgrade I get many spam messages, while there were none before the upgrade.

**Comment by casperklein** [comment]
I am using a "fixed question" and have noticed the same. It's possible to submit nothing or the wrong answer.

**Comment by splitbrain** [comment]
The issue was introduced by c81c7b7a0e07c9e4e7e24b7e972dc9b18c7e8b4c

**Comment by eilko** [comment]
Thanks @splitbrain for your help!

**Comment by ParoTheParrot** [comment]
@eilko : is this issue really solved ? The captcha plugin seems to work ion your site (with Jack Jackrum) .
In case, please update the compatibility information on https://www.dokuwiki.org/plugin:captcha.
Do you patch the plugin manually or through the regularly update mechanism?
TIA, Paro
